name: Maars Website (CI/CD) Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{secrets.SERVER_PORT}}
          script: |
            cd /home/srikar/Maars_HQ
            git pull origin main
            npm install
            cd /home/srikar/
            sudo ./deployhq.sh